### ISSUE TITLE
Art asset building blocks

### ISSUE THREAD

**Issue by GRarer** [GRarer/Aurora#10]
A (possibly incomplete) list of tiles that we need textures for:

# environment
- [x] wasteland
- [x] mountain
- [x] crater

# alien structures
- [x] alien ruins
    - buried into the ground
    - player can build xenotech labs and alien materials recycling plants adjacent to this
- [x] monolith
    - one of these in the map, the seed core will be built on/around this

# early-game structures
- [x] lander pod
    - spacecraft that brings the first colonists and deploys the first buildings
- [x] habitat dome
- [x] solar panels
- [x] greenhouse
    - for growing food to keep colonists alive
- [x] ore processing center
    - factory that turns ore into electronics and building materials
- [x] road
    - connects different colony buildings

# laboratories
- [x] engineering lab
    - workshop for creating new technologies
- [x] psychology lab
    - human experimentation to understand psychology, sociology
- [x] AI alignment lab
    - an office for mathematics/computer science research that unlocks the alternate ending
- [x] xenotechnology lab
    - built adjacent to alien ruins

( it's fine if the labs are slightly different variants on the same base)

# mid-game structures
- [x] mineshaft (built into/on top of mountain)
- [x] arcology
    - tower that houses humans more densely than the habitat dome
- [x] hydroponics greenhouse
    - produces lots of food
- [x] nuclear reactor (fusion?)
- [x] robot hive
    - builds and stores robotic workers
- [x] electronics factory
- [x] structural prefab plant (building materials factory)
- [x] alien materials recycling center
    - built on top of alien ruins (i.e., turns a "ruins" tile into a "recycling plant" tile)
    - mines the ruins for exotic resources

# late game structures
- [x] xenofactory
    - turns exotic resources into high-tech materials like "smart matter" and "superconductors"
- [x] nanotech foundry
    - must be built adjacent to the monolith to build the seed core
- [x] "zero point energy" power plant
    - fancy glowy machine that makes vast amounts of energ
- [x] neural emulation machine
    - must be built adjacent to the seed core to start inititalize the core's world-eating process and win the game
- [x] seed core
    - built on top of/around the monolith
    - self-replicating super computer that hosts a virtual reality for uploaded minds
    - when activated, it starts making copies of itself across the map until the entire world is covered in these machines

**Comment by KingArthurClay** [comment]
I'll get it.

**Comment by GRarer** [comment]
Seong did some nice concept art for the environment: see https://cdn.discordapp.com/attachments/670462882160312330/677644033056702499/unknown.png

**Comment by FreshestJuicebox** [comment]
I am willing to Contribute Nya~

**Comment by GRarer** [comment]
I've created art assets for the tiles listed here. Some of them could be improved, but we now have good-enough textures for all of the planned tile types.
