### ISSUE TITLE
Production Screen UI Improvement

### ISSUE THREAD

**Issue by GRarer** [GRarer/Aurora#11]
I've already got the "Manage Production" screen's functionality working, but it could use better HTML+CSS to make it prettier and more readable. Ideally it would be nice to be able to reorder conversions by drag-and-drop, but that might add a lot of unnecessary complexity.

**Comment by nprindle** [comment]
[Here](https://github.com/nprindle/Aurora/commit/a8a0497e13c5f520bf59af89547c0087c172fda1) is a tentative implementation of drag-and-drop for the production screen, if you want to take a look. The mechanics work pretty well, despite the implementation working around the slightly weird conversion priority setup.
