### ISSUE TITLE
Turn transition screen improvements

### ISSUE THREAD

**Issue by GRarer** [GRarer/Aurora#12]
Right now, the screen you see when you click "next turn" doesn't have anything except a continue button.

I'd like to have this screen show in-universe quotes, like

```
Lorem ipsum dolor sit amet
- John Doe
```
and show a loading animation. After some amount of time (maybe like half a second) the loading animation should then be replaced by a "continue" button.

There should be a list of these quotes, with the loading screen picking a different one at random each time.

**Comment by MGPAlpha** [comment]
I can do this (i don't know how to assign myself to it)

**Comment by GRarer** [comment]
Please look into replacing the loading bar with a looping animation, and make sure that it works on both chromium and firefox
