### ISSUE TITLE
add descriptions to tile projects

### ISSUE THREAD

**Issue by GRarer** [GRarer/Aurora#23]
Tile projects should have text descriptions, since right now there is nothing to tell the player what the effect of, e.g., "strip mining" is. These descriptions should appear below the button for each project in the tile sidebar.

**Comment by MGPAlpha** [comment]
Assign me

**Comment by WCooper32** [comment]
I can write the descriptions (and add some sassy AI snark if you want).

**Comment by GRarer** [comment]
@WCooper32 , I think this would be a good first task to get you started.

You'll want to look at the files `TileProject.ts` and `TileSidebar.ts`

TileProject is the class used for the actions that can be performed on/to/with a tile, like "construct a habitat dome". You'll want to add another field (instance variable) to it's constructor, in the same way that the `title` field is defined.

When you try to build the game (with `npm run build` on the command line) you'll get a bunch of compile-time errors because all of the places where we call the constructor will be missing that field. Follow each of those errors to find the places where the description string needs to be added, and provide some descriptions.

Finally, you'll need to update the user interface to actually show these descriptions below the button for each tile project. This should happen inside `TileSidebar.makeProjectHTML()`.
