### ISSUE TITLE
replace loading bar on turn transition screen

### ISSUE THREAD

**Issue by GRarer** [GRarer/Aurora#28]
The current css-based loading bar works on chrome but not firefox (and I haven't tested it on Safari).

Additionally, I would prefer a looping animation rather than a bar so that the loading animation is not dependent on a specific delay time.

**Comment by MGPAlpha** [comment]
assign me

**Comment by GRarer** [comment]
completed by PR #34 (despite that PR's name not mentioning it, since feature branches got mixed up)
