### ISSUE TITLE
Minor UI issues

### ISSUE THREAD

**Issue by GRarer** [GRarer/Aurora#37]
Comment here about any issues with the appearance or clarity of the UI here.

**Comment by MGPAlpha** [comment]
i can do this whenever theres something here

**Comment by GRarer** [comment]
Places where we could use better css design:
### Research screen
It's not visually clear which descriptions correspond with which buttons. We should at least make the technology names be headings to more clearly separate the list of technologies.
### Production Screen
This screen presents a lot of information, so it's important to do it clearly.

Right now, the inventory takes up a ton of space if the player has each resource. We should make the inventory displays smaller and maybe split them into multiple columns.

We don't need two separate headings for free and costly conversions, and making them separate top-level sections is very confusing.

The unused workers label and the worker resource consumption labels could be merged into one "workers" section.

The production screen would then have 4 sections:
- initial inventory
- resource conversions
- workforce
- final resources

### Tile sidebar
We should put some sort of border around each tile project to make it clear that descriptions correspond with their project's button. The "Projects:" label might be unnecessary, since the presence of buttons with descriptions should be self-explanatory and the name "project" doesn't really convey any information.

**Comment by GRarer** [comment]
I just pushed an improvement to the production screen's UI design

**Comment by GRarer** [comment]
the settings page needs better css styling; for example the slider handles don't match the flat black-and-white design language in the rest of the game
