### ISSUE TITLE
Transition Screen Flavor Text

### ISSUE THREAD

**Issue by WCooper32** [GRarer/Aurora#52]
This is for flavor text quotes to be displayed between turns. The quotes should be from real-life philosophers, visionaries, and computer scientists as well as fictional figures from in-game lore that elaborate on plot, background, etc.

**Comment by GRarer** [comment]
Here's a google doc for the loading-screen quotes. If you have ideas for lore quotes, please leave them as comments/suggestions on the google doc: https://docs.google.com/document/d/1wVvA3AkuTLTeGFdTAcODKxbpUyM38O_q4h93WRQXWKU/edit?usp=sharing

**Comment by GRarer** [comment]
we now have 32 quote entries, 8 quotes from real-world public figures and 24 quotes from fictional in-universe sources that provide information about the mission and the interstellar culture that sent it.
