### ISSUE TITLE
Integrate music with menus

### ISSUE THREAD

**Issue by GRarer** [GRarer/Aurora#67]
We have a volume variable in our settings but it's currently not linked to the actual volume/gain variable of the music system. We should connect these.

Additionally, we need an "enable audio"/"disable audio" button on the main menu to start the music, rather than trying to start the music immediately when the page loads, since autoplaying music without user input is sometimes blocked in chrome.

**Comment by nprindle** [comment]
The current music code doesn't have a way to disable music. `MusicManager.initialize` will start it, but it can't be interrupted after that, other than by setting the volume to 0.
