### ISSUE TITLE
Newtype refactor

### ISSUE THREAD

**Issue by GRarer** [GRarer/Aurora#69]
It would be better to use `newtype` for the places in the music code where note midi numbers and etc are currently encoded as plain `number`s. We discussed this during review of the music pr, but decided to save the refactor for after that code was merged. There might also be some places outside of the music code that would benefit from using `newtype`.

**Comment by nprindle** [comment]
I can take this

**Comment by nprindle** [comment]
So far, I have identified the following distinct types of `number` in the music code:

- `MidiNumber`: corresponds to an absolute note
    - Example: middle C (C4) has a `MidiNumber` of 60

- `Frequency`: the frequency (in Hertz) used by WebAudio to play a note
    - Example: A4 has a `Frequency` of 440

- `Pitch`: offset into 12-tone chromatic scale relative to C
    - Example: an E would have a `Pitch` of 4
    - Can also be outside of this range, but can be normalized with mod
    - Does not represent an absolute note by itself; must be converted to a `MidiNumber` by assigning it to be relative to some octave

- `PitchOffset`: offset, in semitones, from a pitch
    - Example: an E relative to a D would have a `PitchOffset` of 2
    - Used to describe the pitches in a scale relative to the root
    - A "pitch class" is a `PitchOffset[]`

- `Degree`: index into the notes of a scale
    - Example: A G in a C major scale would have a `Degree` of 4, for the fifth degree

- `Scale`: 12-bit bit vector with 1's denoting the degrees
    - If the `i`th 1 is at `1 << n`, then the `i`th degree is `n` semitones up from the root
    - Example: the major scale is `0xab5`, or `0b101010110101` (0, 2, 4, 5, 7, 9, 11)

- `Chord`: also a 12-bit bit vector, but specifically for holding chords, which are subsets of scales

**Comment by nprindle** [comment]
Some things that I think are fine just being `number`s:

- Times, like start times, end times, durations, and the ADSR envelope
- Volume
- Detune coefficients
- BPM
- Subdivisions in rhythms
- Octave index
- Time signatures

These types are fairly different from each other, and would be much harder to confuse than the types above. If any of them are still confusing, though, I can newtype them if necessary.

**Comment by nprindle** [comment]
Resolved by #71
