### ISSUE TITLE
Procgen Music

### ISSUE THREAD

**Issue by GRarer** [GRarer/Aurora#9]
Ideally we'd like to have procedurally-generated music

**Comment by MayMoonsley** [comment]
It's in progress. I have interesting rhythms working.
TODO:

- [ ] Decent sounding percussion.
- [ ] Tonal chord progressions.
- [ ] Melody generation.

**Comment by bbradt** [comment]
i can help with this!

**Comment by MayMoonsley** [comment]
I've been reminded I should update this. Right now there's procedurally generated music. It's just chords and drums for now, but the generation on those two elements is pretty solid in my opinion.
Melody generation is coming along conceptually, though it hasn't yet been implemented. I'll do that before I work on audio effects like delay and stuff.

**Comment by GRarer** [comment]
The current music generation is good enough, and we are no longer planning to have a more sophisticated system, at least not in time for the vgdev spring demo
